apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${SERVICE_MONITOR_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: ${METRICS_SERVICE_NAME}
  endpoints:
    - port: metrics
      path: ${METRICS_PATH}
      interval: ${METRICS_SCRAPE_INTERVAL}