apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-monitor
  namespace: llm-demo
spec:
  selector:
    matchLabels:
      app: vllm-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
