apiVersion: v1
kind: Service
metadata:
  name: ${METRICS_SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${METRICS_SERVICE_NAME}
spec:
  selector:
    app.kubernetes.io/name: ${WORKLOAD_LABEL_NAME}
    kserve.io/component: workload
  ports:
    - name: metrics
      port: ${METRICS_PORT}
      targetPort: ${METRICS_PORT}