apiVersion: v1
kind: Service
metadata:
  name: vllm-metrics
  namespace: llm-demo
  labels:
    app: vllm-metrics
spec:
  selector:
    app.kubernetes.io/name: facebook-opt-125m
    kserve.io/component: workload
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
