policy_key: keda-waiting-requests
policy_type: keda-prometheus

min_replicas: 1
max_replicas: 5
polling_interval: 5
cooldown_period: 30

prometheus:
  server_address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
  metric_name: vllm_waiting_requests
  query: |
    sum(
      vllm:num_requests_waiting{
        namespace="llm-demo"
      }
    )
  threshold: "1"
  activation_threshold: "1"