policy_key: keda-token-cache-composite
policy_type: keda-composite

min_replicas: 1
max_replicas: 5
polling_interval: 5
cooldown_period: 45

prometheus:
  server_address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

advanced:
  scaling_modifiers:
    formula: "(token_workload * 0.9) + (kv_cache_pct * 8)"
    target: "6"
    activation_target: "1"

triggers:
  - name: token_workload
    metric_name: vllm_token_workload
    query: |
      (
        sum(
          rate(vllm:prompt_tokens_total{model_name="Qwen/Qwen2.5-0.5B-Instruct"}[1m])
        )
      )
      +
      0.5 *
      (
        sum(
          rate(vllm:generation_tokens_total{model_name="Qwen/Qwen2.5-0.5B-Instruct"}[1m])
        )
      )
    threshold: "6"
    activation_threshold: "1"

  - name: waiting
    metric_name: vllm_waiting_requests
    query: |
      sum(
        vllm:num_requests_waiting{model_name="Qwen/Qwen2.5-0.5B-Instruct"}
      )
    threshold: "1"
    activation_threshold: "1"

  - name: kv_cache_pct
    metric_name: vllm_kv_cache_usage_percent
    query: |
      avg(
        vllm:kv_cache_usage_perc{model_name="Qwen/Qwen2.5-0.5B-Instruct"}
      )
    threshold: "0.03"
    activation_threshold: "0.01"