apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: distilgpt2
  namespace: llm-demo
spec:
  model:
    uri: hf://distilbert/distilgpt2
    name: distilgpt2
  replicas: 1
  template:
    containers:
      - name: main
        image: quay.io/pierdipi/vllm-cpu:latest
        securityContext:
          runAsNonRoot: false
        env:
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "100m"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
  router:
    gateway: {}
    route: {}
    scheduler: {}
