apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: facebook-opt-125m
  namespace: llm-demo
spec:
  model:
    uri: hf://facebook/opt-125m
    name: facebook/opt-125m
  replicas: 1
  template:
    containers:
      - name: main
        image: quay.io/pierdipi/vllm-cpu:latest
        securityContext:
          runAsNonRoot: false
        env:
          - name: VLLM_LOGGING_LEVEL
            value: INFO
        resources:
          requests:
            cpu: "500m"
            memory: 4Gi
          limits:
            cpu: "2"
            memory: 10Gi
  router:
    gateway: {}
    route: {}
    scheduler: {}
